source ~/.zshrc.custom
source ~/.zshrc.work

export PATH=/Users/brianacoppard/bin:$PATH
export PATH="/usr/local/opt/ruby/bin:$PATH"
export PATH="/usr/local/opt/mysql@5.7/bin:$PATH"
source /Users/bcoppard/Code/zendesk/scooter/scripts/shell/scooter.sh
source ~/Code/zendesk/kubectl_config/dotfiles/kubectl_stuff.bash

source /opt/homebrew/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc
source /opt/homebrew/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.zsh.inc

export SCOOTER_KUBERNETES_CONTEXT=scooter-euc1
# BEGIN ZDI
export DOCKER_FOR_MAC_ENABLED=true
source /Users/bcoppard/Code/zendesk/zdi/dockmaster/zdi.sh
# END ZDI
